[theme]
primaryColor = "#0D9648"
backgroundColor = "#F3F7F6"
secondaryBackgroundColor = "#EAF0EF"
textColor = "#173B3D"
font = "sans serif"

[server]
maxUploadSize = 2

[browser]
gatherUsageStats = false
